apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
  # These are deployment set labels.
  labels:
    purpose: blue-green
    project: roboshop
    color: green
spec:
  replicas: 4
  selector: 
  # These labels are used to select pods.
    matchLabels:
      purpose: blue-green
      project: roboshop  
      color: green
  # pod definition    
  template:
    metadata:
      labels:
        purpose: blue-green
        project: roboshop
        color: green
    spec:    
      containers:
      - name: nginx
      # Deployment respects image changes.
        image: nginx:mainline-alpine3.23-perl